version: '2'

services:
  db:
    image: postgres
    environment:
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"

  web:
    image: rindrics/gtd-django:latest
    environment:
    - SECRET_KEY=${SECRET_KEY}
    - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    - DATABASE_NAME=${DATABASE_NAME}
    - DATABASE_USER=${DATABASE_USER}
    - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    - DATABASE_HOST=${DATABASE_HOST}
    - DATABASE_PORT=${DATABASE_PORT}
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    working_dir: /code
    ports:
      - 8000:8000
    depends_on:
      - db
